[package]
name = "q_learning"
version = "0.1.0"
authors = ["richardworrall <richard.e.worrall@gmail.com>"]
edition = "2018"


[lib]
name = "blackjack"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.2"
text_io = "0.1.8"

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]